spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudkitchen
    username: postgres
    password: 6441
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: false
    open-in-view: false